// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: dashboardpb/dashboard.proto

package dashboardpb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	commonpb "sensor-data-service.backend/api/pb/commonpb"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LayoutJson    string                 `protobuf:"bytes,4,opt,name=layout_json,json=layoutJson,proto3" json:"layout_json,omitempty"` // full config của dashboard (panel, layout)
	CreatedBy     int32                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_dashboardpb_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardpb_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_dashboardpb_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *Dashboard) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dashboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dashboard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dashboard) GetLayoutJson() string {
	if x != nil {
		return x.LayoutJson
	}
	return ""
}

func (x *Dashboard) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Dashboard) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Dashboard) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Dashboard) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Dashboard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DashboardID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardID) Reset() {
	*x = DashboardID{}
	mi := &file_dashboardpb_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardID) ProtoMessage() {}

func (x *DashboardID) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardpb_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardID.ProtoReflect.Descriptor instead.
func (*DashboardID) Descriptor() ([]byte, []int) {
	return file_dashboardpb_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DashboardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboards    []*Dashboard           `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardList) Reset() {
	*x = DashboardList{}
	mi := &file_dashboardpb_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardList) ProtoMessage() {}

func (x *DashboardList) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardpb_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardList.ProtoReflect.Descriptor instead.
func (*DashboardList) Descriptor() ([]byte, []int) {
	return file_dashboardpb_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardList) GetDashboards() []*Dashboard {
	if x != nil {
		return x.Dashboards
	}
	return nil
}

type SaveDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *Dashboard             `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDashboardRequest) Reset() {
	*x = SaveDashboardRequest{}
	mi := &file_dashboardpb_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDashboardRequest) ProtoMessage() {}

func (x *SaveDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardpb_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDashboardRequest.ProtoReflect.Descriptor instead.
func (*SaveDashboardRequest) Descriptor() ([]byte, []int) {
	return file_dashboardpb_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *SaveDashboardRequest) GetDashboard() *Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

var File_dashboardpb_dashboard_proto protoreflect.FileDescriptor

const file_dashboardpb_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1bdashboardpb/dashboard.proto\x12\tdashboard\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15commonpb/common.proto\"\x81\x02\n" +
	"\tDashboard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlayout_json\x18\x04 \x01(\tR\n" +
	"layoutJson\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x05R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\x1d\n" +
	"\vDashboardID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\rDashboardList\x124\n" +
	"\n" +
	"dashboards\x18\x01 \x03(\v2\x14.dashboard.DashboardR\n" +
	"dashboards\"J\n" +
	"\x14SaveDashboardRequest\x122\n" +
	"\tdashboard\x18\x01 \x01(\v2\x14.dashboard.DashboardR\tdashboard2\x96\x03\n" +
	"\x10DashboardService\x12]\n" +
	"\fGetDashboard\x12\x16.dashboard.DashboardID\x1a\x18.common.StandardResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v0/dashboards/{id}\x12Z\n" +
	"\x0eListDashboards\x12\x16.google.protobuf.Empty\x1a\x18.common.StandardResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v0/dashboards\x12e\n" +
	"\rSaveDashboard\x12\x1f.dashboard.SaveDashboardRequest\x1a\x18.common.StandardResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v0/dashboards\x12`\n" +
	"\x0fDeleteDashboard\x12\x16.dashboard.DashboardID\x1a\x18.common.StandardResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v0/dashboards/{id}B<Z:sensor-data-service.backend/api/pb/dashboardpb;dashboardpbb\x06proto3"

var (
	file_dashboardpb_dashboard_proto_rawDescOnce sync.Once
	file_dashboardpb_dashboard_proto_rawDescData []byte
)

func file_dashboardpb_dashboard_proto_rawDescGZIP() []byte {
	file_dashboardpb_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboardpb_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboardpb_dashboard_proto_rawDesc), len(file_dashboardpb_dashboard_proto_rawDesc)))
	})
	return file_dashboardpb_dashboard_proto_rawDescData
}

var file_dashboardpb_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dashboardpb_dashboard_proto_goTypes = []any{
	(*Dashboard)(nil),                 // 0: dashboard.Dashboard
	(*DashboardID)(nil),               // 1: dashboard.DashboardID
	(*DashboardList)(nil),             // 2: dashboard.DashboardList
	(*SaveDashboardRequest)(nil),      // 3: dashboard.SaveDashboardRequest
	(*empty.Empty)(nil),               // 4: google.protobuf.Empty
	(*commonpb.StandardResponse)(nil), // 5: common.StandardResponse
}
var file_dashboardpb_dashboard_proto_depIdxs = []int32{
	0, // 0: dashboard.DashboardList.dashboards:type_name -> dashboard.Dashboard
	0, // 1: dashboard.SaveDashboardRequest.dashboard:type_name -> dashboard.Dashboard
	1, // 2: dashboard.DashboardService.GetDashboard:input_type -> dashboard.DashboardID
	4, // 3: dashboard.DashboardService.ListDashboards:input_type -> google.protobuf.Empty
	3, // 4: dashboard.DashboardService.SaveDashboard:input_type -> dashboard.SaveDashboardRequest
	1, // 5: dashboard.DashboardService.DeleteDashboard:input_type -> dashboard.DashboardID
	5, // 6: dashboard.DashboardService.GetDashboard:output_type -> common.StandardResponse
	5, // 7: dashboard.DashboardService.ListDashboards:output_type -> common.StandardResponse
	5, // 8: dashboard.DashboardService.SaveDashboard:output_type -> common.StandardResponse
	5, // 9: dashboard.DashboardService.DeleteDashboard:output_type -> common.StandardResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dashboardpb_dashboard_proto_init() }
func file_dashboardpb_dashboard_proto_init() {
	if File_dashboardpb_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboardpb_dashboard_proto_rawDesc), len(file_dashboardpb_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboardpb_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboardpb_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboardpb_dashboard_proto_msgTypes,
	}.Build()
	File_dashboardpb_dashboard_proto = out.File
	file_dashboardpb_dashboard_proto_goTypes = nil
	file_dashboardpb_dashboard_proto_depIdxs = nil
}
