// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: parameterpb/parameter.proto

package parameterpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	commonpb "sensor-data-service.backend/api/pb/commonpb"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_parameterpb_parameter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{0}
}

type ParameterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterRequest) Reset() {
	*x = ParameterRequest{}
	mi := &file_parameterpb_parameter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterRequest) ProtoMessage() {}

func (x *ParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterRequest.ProtoReflect.Descriptor instead.
func (*ParameterRequest) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{1}
}

func (x *ParameterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ParameterCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit           string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	ParameterGroup string                 `protobuf:"bytes,3,opt,name=parameter_group,json=parameterGroup,proto3" json:"parameter_group,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParameterCreateRequest) Reset() {
	*x = ParameterCreateRequest{}
	mi := &file_parameterpb_parameter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterCreateRequest) ProtoMessage() {}

func (x *ParameterCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterCreateRequest.ProtoReflect.Descriptor instead.
func (*ParameterCreateRequest) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterCreateRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ParameterCreateRequest) GetParameterGroup() string {
	if x != nil {
		return x.ParameterGroup
	}
	return ""
}

func (x *ParameterCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ParameterUpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit           string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	ParameterGroup string                 `protobuf:"bytes,4,opt,name=parameter_group,json=parameterGroup,proto3" json:"parameter_group,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParameterUpdateRequest) Reset() {
	*x = ParameterUpdateRequest{}
	mi := &file_parameterpb_parameter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterUpdateRequest) ProtoMessage() {}

func (x *ParameterUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterUpdateRequest.ProtoReflect.Descriptor instead.
func (*ParameterUpdateRequest) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{3}
}

func (x *ParameterUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParameterUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterUpdateRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ParameterUpdateRequest) GetParameterGroup() string {
	if x != nil {
		return x.ParameterGroup
	}
	return ""
}

func (x *ParameterUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ParameterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit           string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	ParameterGroup string                 `protobuf:"bytes,4,opt,name=parameter_group,json=parameterGroup,proto3" json:"parameter_group,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParameterResponse) Reset() {
	*x = ParameterResponse{}
	mi := &file_parameterpb_parameter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterResponse) ProtoMessage() {}

func (x *ParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterResponse.ProtoReflect.Descriptor instead.
func (*ParameterResponse) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{4}
}

func (x *ParameterResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParameterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ParameterResponse) GetParameterGroup() string {
	if x != nil {
		return x.ParameterGroup
	}
	return ""
}

func (x *ParameterResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ParameterResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ParameterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ParameterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*ParameterResponse   `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterListResponse) Reset() {
	*x = ParameterListResponse{}
	mi := &file_parameterpb_parameter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterListResponse) ProtoMessage() {}

func (x *ParameterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterListResponse.ProtoReflect.Descriptor instead.
func (*ParameterListResponse) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{5}
}

func (x *ParameterListResponse) GetParameters() []*ParameterResponse {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_parameterpb_parameter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parameterpb_parameter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_parameterpb_parameter_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_parameterpb_parameter_proto protoreflect.FileDescriptor

const file_parameterpb_parameter_proto_rawDesc = "" +
	"\n" +
	"\x1bparameterpb/parameter.proto\x12\tparameter\x1a\x1cgoogle/api/annotations.proto\x1a\x15commonpb/common.proto\"\a\n" +
	"\x05Empty\"\"\n" +
	"\x10ParameterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x8b\x01\n" +
	"\x16ParameterCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12'\n" +
	"\x0fparameter_group\x18\x03 \x01(\tR\x0eparameterGroup\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x9b\x01\n" +
	"\x16ParameterUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12'\n" +
	"\x0fparameter_group\x18\x04 \x01(\tR\x0eparameterGroup\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xec\x01\n" +
	"\x11ParameterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12'\n" +
	"\x0fparameter_group\x18\x04 \x01(\tR\x0eparameterGroup\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"U\n" +
	"\x15ParameterListResponse\x12<\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1c.parameter.ParameterResponseR\n" +
	"parameters\"(\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8e\x04\n" +
	"\x10ParameterService\x12T\n" +
	"\x0eListParameters\x12\x10.parameter.Empty\x1a\x18.common.StandardResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v0/parameters\x12b\n" +
	"\fGetParameter\x12\x1b.parameter.ParameterRequest\x1a\x18.common.StandardResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v0/parameters/{id}\x12i\n" +
	"\x0fCreateParameter\x12!.parameter.ParameterCreateRequest\x1a\x18.common.StandardResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v0/parameters\x12n\n" +
	"\x0fUpdateParameter\x12!.parameter.ParameterUpdateRequest\x1a\x18.common.StandardResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v0/parameters/{id}\x12e\n" +
	"\x0fDeleteParameter\x12\x1b.parameter.ParameterRequest\x1a\x18.common.StandardResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v0/parameters/{id}B<Z:sensor-data-service.backend/api/pb/parameterpb;parameterpbb\x06proto3"

var (
	file_parameterpb_parameter_proto_rawDescOnce sync.Once
	file_parameterpb_parameter_proto_rawDescData []byte
)

func file_parameterpb_parameter_proto_rawDescGZIP() []byte {
	file_parameterpb_parameter_proto_rawDescOnce.Do(func() {
		file_parameterpb_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parameterpb_parameter_proto_rawDesc), len(file_parameterpb_parameter_proto_rawDesc)))
	})
	return file_parameterpb_parameter_proto_rawDescData
}

var file_parameterpb_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_parameterpb_parameter_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: parameter.Empty
	(*ParameterRequest)(nil),          // 1: parameter.ParameterRequest
	(*ParameterCreateRequest)(nil),    // 2: parameter.ParameterCreateRequest
	(*ParameterUpdateRequest)(nil),    // 3: parameter.ParameterUpdateRequest
	(*ParameterResponse)(nil),         // 4: parameter.ParameterResponse
	(*ParameterListResponse)(nil),     // 5: parameter.ParameterListResponse
	(*DeleteResponse)(nil),            // 6: parameter.DeleteResponse
	(*commonpb.StandardResponse)(nil), // 7: common.StandardResponse
}
var file_parameterpb_parameter_proto_depIdxs = []int32{
	4, // 0: parameter.ParameterListResponse.parameters:type_name -> parameter.ParameterResponse
	0, // 1: parameter.ParameterService.ListParameters:input_type -> parameter.Empty
	1, // 2: parameter.ParameterService.GetParameter:input_type -> parameter.ParameterRequest
	2, // 3: parameter.ParameterService.CreateParameter:input_type -> parameter.ParameterCreateRequest
	3, // 4: parameter.ParameterService.UpdateParameter:input_type -> parameter.ParameterUpdateRequest
	1, // 5: parameter.ParameterService.DeleteParameter:input_type -> parameter.ParameterRequest
	7, // 6: parameter.ParameterService.ListParameters:output_type -> common.StandardResponse
	7, // 7: parameter.ParameterService.GetParameter:output_type -> common.StandardResponse
	7, // 8: parameter.ParameterService.CreateParameter:output_type -> common.StandardResponse
	7, // 9: parameter.ParameterService.UpdateParameter:output_type -> common.StandardResponse
	7, // 10: parameter.ParameterService.DeleteParameter:output_type -> common.StandardResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_parameterpb_parameter_proto_init() }
func file_parameterpb_parameter_proto_init() {
	if File_parameterpb_parameter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parameterpb_parameter_proto_rawDesc), len(file_parameterpb_parameter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parameterpb_parameter_proto_goTypes,
		DependencyIndexes: file_parameterpb_parameter_proto_depIdxs,
		MessageInfos:      file_parameterpb_parameter_proto_msgTypes,
	}.Build()
	File_parameterpb_parameter_proto = out.File
	file_parameterpb_parameter_proto_goTypes = nil
	file_parameterpb_parameter_proto_depIdxs = nil
}
