// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: metricdatapb/metricdata.proto

package metricdatapb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	commonpb "sensor-data-service.backend/api/pb/commonpb"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetType int32

const (
	TargetType_UNKNOWN     TargetType = 0
	TargetType_STATION     TargetType = 1
	TargetType_WATER_BODY  TargetType = 2
	TargetType_CATCHMENT   TargetType = 3
	TargetType_RIVER_BASIN TargetType = 4
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STATION",
		2: "WATER_BODY",
		3: "CATCHMENT",
		4: "RIVER_BASIN",
	}
	TargetType_value = map[string]int32{
		"UNKNOWN":     0,
		"STATION":     1,
		"WATER_BODY":  2,
		"CATCHMENT":   3,
		"RIVER_BASIN": 4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_metricdatapb_metricdata_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_metricdatapb_metricdata_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{0}
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TimeRange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type SeriesSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=metricdata.TargetType" json:"target_type,omitempty"`
	TargetId      int32                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MetricId      int32                  `protobuf:"varint,4,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesSelector) Reset() {
	*x = SeriesSelector{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesSelector) ProtoMessage() {}

func (x *SeriesSelector) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesSelector.ProtoReflect.Descriptor instead.
func (*SeriesSelector) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{1}
}

func (x *SeriesSelector) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *SeriesSelector) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_UNKNOWN
}

func (x *SeriesSelector) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SeriesSelector) GetMetricId() int32 {
	if x != nil {
		return x.MetricId
	}
	return 0
}

type ForecastConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TimeStep      int32                  `protobuf:"varint,2,opt,name=time_step,json=timeStep,proto3" json:"time_step,omitempty"`
	Horizon       int32                  `protobuf:"varint,3,opt,name=horizon,proto3" json:"horizon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastConfig) Reset() {
	*x = ForecastConfig{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastConfig) ProtoMessage() {}

func (x *ForecastConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastConfig.ProtoReflect.Descriptor instead.
func (*ForecastConfig) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{2}
}

func (x *ForecastConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ForecastConfig) GetTimeStep() int32 {
	if x != nil {
		return x.TimeStep
	}
	return 0
}

func (x *ForecastConfig) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

type MetricSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChartType     string                 `protobuf:"bytes,1,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	StepSeconds   int32                  `protobuf:"varint,3,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	Forecast      *ForecastConfig        `protobuf:"bytes,4,opt,name=forecast,proto3" json:"forecast,omitempty"`
	Series        []*SeriesSelector      `protobuf:"bytes,5,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeriesRequest) Reset() {
	*x = MetricSeriesRequest{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeriesRequest) ProtoMessage() {}

func (x *MetricSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeriesRequest.ProtoReflect.Descriptor instead.
func (*MetricSeriesRequest) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{3}
}

func (x *MetricSeriesRequest) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

func (x *MetricSeriesRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *MetricSeriesRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *MetricSeriesRequest) GetForecast() *ForecastConfig {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *MetricSeriesRequest) GetSeries() []*SeriesSelector {
	if x != nil {
		return x.Series
	}
	return nil
}

type MetricPoint struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Datetime string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Value    float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// float local_error = 3;
	TrendAnomaly  bool `protobuf:"varint,3,opt,name=trend_anomaly,json=trendAnomaly,proto3" json:"trend_anomaly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{4}
}

func (x *MetricPoint) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *MetricPoint) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetTrendAnomaly() bool {
	if x != nil {
		return x.TrendAnomaly
	}
	return false
}

type SeriesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=metricdata.TargetType" json:"target_type,omitempty"`
	TargetId      int32                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MetricId      int32                  `protobuf:"varint,4,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Series        []*MetricPoint         `protobuf:"bytes,5,rep,name=series,proto3" json:"series,omitempty"`
	Forecast      []*MetricPoint         `protobuf:"bytes,6,rep,name=forecast,proto3" json:"forecast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesData) Reset() {
	*x = SeriesData{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesData) ProtoMessage() {}

func (x *SeriesData) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesData.ProtoReflect.Descriptor instead.
func (*SeriesData) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{5}
}

func (x *SeriesData) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *SeriesData) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_UNKNOWN
}

func (x *SeriesData) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SeriesData) GetMetricId() int32 {
	if x != nil {
		return x.MetricId
	}
	return 0
}

func (x *SeriesData) GetSeries() []*MetricPoint {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *SeriesData) GetForecast() []*MetricPoint {
	if x != nil {
		return x.Forecast
	}
	return nil
}

type MetricSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SeriesData          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeriesResponse) Reset() {
	*x = MetricSeriesResponse{}
	mi := &file_metricdatapb_metricdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeriesResponse) ProtoMessage() {}

func (x *MetricSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metricdatapb_metricdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeriesResponse.ProtoReflect.Descriptor instead.
func (*MetricSeriesResponse) Descriptor() ([]byte, []int) {
	return file_metricdatapb_metricdata_proto_rawDescGZIP(), []int{6}
}

func (x *MetricSeriesResponse) GetResults() []*SeriesData {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_metricdatapb_metricdata_proto protoreflect.FileDescriptor

const file_metricdatapb_metricdata_proto_rawDesc = "" +
	"\n" +
	"\x1dmetricdatapb/metricdata.proto\x12\n" +
	"metricdata\x1a\x1cgoogle/api/annotations.proto\x1a\x15commonpb/common.proto\"/\n" +
	"\tTimeRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\x9a\x01\n" +
	"\x0eSeriesSelector\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x127\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x16.metricdata.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x05R\btargetId\x12\x1b\n" +
	"\tmetric_id\x18\x04 \x01(\x05R\bmetricId\"a\n" +
	"\x0eForecastConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\ttime_step\x18\x02 \x01(\x05R\btimeStep\x12\x18\n" +
	"\ahorizon\x18\x03 \x01(\x05R\ahorizon\"\xf9\x01\n" +
	"\x13MetricSeriesRequest\x12\x1d\n" +
	"\n" +
	"chart_type\x18\x01 \x01(\tR\tchartType\x124\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x15.metricdata.TimeRangeR\ttimeRange\x12!\n" +
	"\fstep_seconds\x18\x03 \x01(\x05R\vstepSeconds\x126\n" +
	"\bforecast\x18\x04 \x01(\v2\x1a.metricdata.ForecastConfigR\bforecast\x122\n" +
	"\x06series\x18\x05 \x03(\v2\x1a.metricdata.SeriesSelectorR\x06series\"d\n" +
	"\vMetricPoint\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12#\n" +
	"\rtrend_anomaly\x18\x03 \x01(\bR\ftrendAnomaly\"\xfc\x01\n" +
	"\n" +
	"SeriesData\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x127\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x16.metricdata.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x05R\btargetId\x12\x1b\n" +
	"\tmetric_id\x18\x04 \x01(\x05R\bmetricId\x12/\n" +
	"\x06series\x18\x05 \x03(\v2\x17.metricdata.MetricPointR\x06series\x123\n" +
	"\bforecast\x18\x06 \x03(\v2\x17.metricdata.MetricPointR\bforecast\"H\n" +
	"\x14MetricSeriesResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.metricdata.SeriesDataR\aresults*V\n" +
	"\n" +
	"TargetType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTATION\x10\x01\x12\x0e\n" +
	"\n" +
	"WATER_BODY\x10\x02\x12\r\n" +
	"\tCATCHMENT\x10\x03\x12\x0f\n" +
	"\vRIVER_BASIN\x10\x042\x7f\n" +
	"\x11MetricDataService\x12j\n" +
	"\x0fGetMetricSeries\x12\x1f.metricdata.MetricSeriesRequest\x1a\x18.common.StandardResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v0/metric_seriesB>Z<sensor-data-service.backend/api/pb/metricdatapb;metricdatapbb\x06proto3"

var (
	file_metricdatapb_metricdata_proto_rawDescOnce sync.Once
	file_metricdatapb_metricdata_proto_rawDescData []byte
)

func file_metricdatapb_metricdata_proto_rawDescGZIP() []byte {
	file_metricdatapb_metricdata_proto_rawDescOnce.Do(func() {
		file_metricdatapb_metricdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metricdatapb_metricdata_proto_rawDesc), len(file_metricdatapb_metricdata_proto_rawDesc)))
	})
	return file_metricdatapb_metricdata_proto_rawDescData
}

var file_metricdatapb_metricdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metricdatapb_metricdata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_metricdatapb_metricdata_proto_goTypes = []any{
	(TargetType)(0),                   // 0: metricdata.TargetType
	(*TimeRange)(nil),                 // 1: metricdata.TimeRange
	(*SeriesSelector)(nil),            // 2: metricdata.SeriesSelector
	(*ForecastConfig)(nil),            // 3: metricdata.ForecastConfig
	(*MetricSeriesRequest)(nil),       // 4: metricdata.MetricSeriesRequest
	(*MetricPoint)(nil),               // 5: metricdata.MetricPoint
	(*SeriesData)(nil),                // 6: metricdata.SeriesData
	(*MetricSeriesResponse)(nil),      // 7: metricdata.MetricSeriesResponse
	(*commonpb.StandardResponse)(nil), // 8: common.StandardResponse
}
var file_metricdatapb_metricdata_proto_depIdxs = []int32{
	0, // 0: metricdata.SeriesSelector.target_type:type_name -> metricdata.TargetType
	1, // 1: metricdata.MetricSeriesRequest.time_range:type_name -> metricdata.TimeRange
	3, // 2: metricdata.MetricSeriesRequest.forecast:type_name -> metricdata.ForecastConfig
	2, // 3: metricdata.MetricSeriesRequest.series:type_name -> metricdata.SeriesSelector
	0, // 4: metricdata.SeriesData.target_type:type_name -> metricdata.TargetType
	5, // 5: metricdata.SeriesData.series:type_name -> metricdata.MetricPoint
	5, // 6: metricdata.SeriesData.forecast:type_name -> metricdata.MetricPoint
	6, // 7: metricdata.MetricSeriesResponse.results:type_name -> metricdata.SeriesData
	4, // 8: metricdata.MetricDataService.GetMetricSeries:input_type -> metricdata.MetricSeriesRequest
	8, // 9: metricdata.MetricDataService.GetMetricSeries:output_type -> common.StandardResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_metricdatapb_metricdata_proto_init() }
func file_metricdatapb_metricdata_proto_init() {
	if File_metricdatapb_metricdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metricdatapb_metricdata_proto_rawDesc), len(file_metricdatapb_metricdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metricdatapb_metricdata_proto_goTypes,
		DependencyIndexes: file_metricdatapb_metricdata_proto_depIdxs,
		EnumInfos:         file_metricdatapb_metricdata_proto_enumTypes,
		MessageInfos:      file_metricdatapb_metricdata_proto_msgTypes,
	}.Build()
	File_metricdatapb_metricdata_proto = out.File
	file_metricdatapb_metricdata_proto_goTypes = nil
	file_metricdatapb_metricdata_proto_depIdxs = nil
}
