// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: metricdatapb/metricdata.proto

package metricdatapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "sensor-data-service.backend/api/pb/commonpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricDataService_GetMetricSeries_FullMethodName = "/metricdata.MetricDataService/GetMetricSeries"
)

// MetricDataServiceClient is the client API for MetricDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricDataServiceClient interface {
	GetMetricSeries(ctx context.Context, in *MetricSeriesRequest, opts ...grpc.CallOption) (*commonpb.StandardResponse, error)
}

type metricDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricDataServiceClient(cc grpc.ClientConnInterface) MetricDataServiceClient {
	return &metricDataServiceClient{cc}
}

func (c *metricDataServiceClient) GetMetricSeries(ctx context.Context, in *MetricSeriesRequest, opts ...grpc.CallOption) (*commonpb.StandardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.StandardResponse)
	err := c.cc.Invoke(ctx, MetricDataService_GetMetricSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricDataServiceServer is the server API for MetricDataService service.
// All implementations must embed UnimplementedMetricDataServiceServer
// for forward compatibility.
type MetricDataServiceServer interface {
	GetMetricSeries(context.Context, *MetricSeriesRequest) (*commonpb.StandardResponse, error)
	mustEmbedUnimplementedMetricDataServiceServer()
}

// UnimplementedMetricDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricDataServiceServer struct{}

func (UnimplementedMetricDataServiceServer) GetMetricSeries(context.Context, *MetricSeriesRequest) (*commonpb.StandardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricSeries not implemented")
}
func (UnimplementedMetricDataServiceServer) mustEmbedUnimplementedMetricDataServiceServer() {}
func (UnimplementedMetricDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMetricDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricDataServiceServer will
// result in compilation errors.
type UnsafeMetricDataServiceServer interface {
	mustEmbedUnimplementedMetricDataServiceServer()
}

func RegisterMetricDataServiceServer(s grpc.ServiceRegistrar, srv MetricDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricDataService_ServiceDesc, srv)
}

func _MetricDataService_GetMetricSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricDataServiceServer).GetMetricSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricDataService_GetMetricSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricDataServiceServer).GetMetricSeries(ctx, req.(*MetricSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricDataService_ServiceDesc is the grpc.ServiceDesc for MetricDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metricdata.MetricDataService",
	HandlerType: (*MetricDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricSeries",
			Handler:    _MetricDataService_GetMetricSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metricdatapb/metricdata.proto",
}
